### ISSUE TITLE
NullPointerException in findImageId

### ISSUE THREAD

**Issue by tayloryork** [alexec/docker-java-orchestration#19]
I am encountering a NullPointerException when trying to build a simple docker image.  As you can see from the output, the /images rest call returns a list of images, but then the findImageIds fails throwing a null pointer.

The project can be checked out at https://github.com/tayloryork/war-deployment-examples

Thank you.

[INFO] 
[INFO] Successfully built 87feb4e73295
[INFO] 
[INFO] 4 * Sending client request on thread main
4 > GET https://192.168.59.103:2376/v1.4.1/images/json?all=0
4 > Accept: application/json

[INFO] 5 * Client response received on thread main
5 < 200
5 < Content-Length: 1289
5 < Content-Type: application/json
5 < Date: Tue, 03 Feb 2015 07:52:17 GMT
[{"Created":1422949937,"Id":"87feb4e73295ac4c7b27b2ba215e429f1fc19c9bcc2e5852ebf2be1c9c8b8da4","Repository":"registry/war-deployment-examples","Size":0,"Tag":"0.0.1-SNAPSHOT","VirtualSize":451821911}
,{"Created":1422949905,"Id":"baa09ed41bc686aa2e40e8617513149c848418f7373be51836194f9c63e8e121","Repository":"\u003cnone\u003e","Size":0,"Tag":"\u003cnone\u003e","VirtualSize":451821911}
,{"Created":1422949829,"Id":"71f2f551885dd6551e5b0d3a51d0a70e5f297cab299cb7ddb2bed8ce02f100ec","Repository":"\u003cnone\u003e","Size":0,"Tag":"\u003cnone\u003e","VirtualSize":451821911}
,{"Created":1422947997,"Id":"f09674583ae7228ed1bd63acac3e267ba278de5f30ab657e86466b5132031655","Repository":"\u003cnone\u003e","Size":0,"Tag":"\u003cnone\u003e","VirtualSize":451821911}
,{"Created":1422947841,"Id":"a4e8153c9cea66b14c66ace8cd978a337a085355b23c7f10ee89c0a185a3be3e","Repository":"registry/war-deployment-examples","Size":0,"Tag":"1111","VirtualSize":451821911}
,{"Created":1422470238,"Id":"5ba9dab47459d81c0037ca3836a368a4f8ce5050505ce89720e1fb8839ea048a","Repository":"ubuntu","Size":0,"Tag":"14.04","VirtualSize":188305222}
,{"Created":1420481143,"Id":"510cf09a79863a3387f8929f9b2171e05bb9624c26f999fa65c833934e61fea1","Repository":"centos","Size":202611551,"Tag":"centos6","VirtualSize":202611551}
]

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.813s
[INFO] Finished at: Tue Feb 03 01:52:13 CST 2015
[INFO] Final Memory: 29M/228M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.4.0:package (default-cli) on project war-deployment-examples: null: MojoExecutionException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.4.0:package (default-cli) on project war-deployment-examples: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException
	at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:125)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.NullPointerException
	at com.alexecollins.docker.orchestration.Repo.findImageId(Repo.java:103)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.build(DockerOrchestrator.java:188)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.build(DockerOrchestrator.java:142)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.build(DockerOrchestrator.java:397)
	at com.alexecollins.docker.mojo.PackageMojo.doExecute(PackageMojo.java:16)
	at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:122)
	... 21 more
[ERROR]

**Comment by alexec** [comment]
OK. Please remove these two lines from your `pom.xml`:

~~~
                                       <!-- docker version -->
                                       <version>1.4.1</version>
~~~

**Comment by tayloryork** [comment]
Thank you!

You may want to update 
https://github.com/alexec/docker-maven-plugin/blob/master/USAGE.md

I started with the example given on the USAGE page, but in the end I had to remove <version></version> and replace <dockerCertPath></dockerCertPath> with <certificatePath></certificatePath>

**Comment by tayloryork** [comment]
Oh and sorry for filing the defect here - I thought it was a docker-java-orchestration issue, not a docker-maven-plugin configuration issue.
