### ISSUE TITLE
Exception when copying files using NIO

### ISSUE THREAD

**Issue by alexec** [alexec/docker-java-orchestration#59]
Hi @marcust ,

After merging your changes,  the integration tests (https://circleci.com/gh/alexec/docker-maven-plugin/322) produce this error:

~~~
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[INFO] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
[INFO] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
[INFO] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
[INFO] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
[INFO] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
[INFO] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:606)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Caused by: org.apache.maven.plugin.MojoExecutionException: java.nio.file.DirectoryNotEmptyException: /home/ubuntu/docker-maven-plugin/target/it/build-test-it/target/docker/app
[INFO] 	at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:164)
[INFO] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[INFO] 	... 19 more
[INFO] Caused by: com.alexecollins.docker.orchestration.OrchestrationException: java.nio.file.DirectoryNotEmptyException: /home/ubuntu/docker-maven-plugin/target/it/build-test-it/target/docker/app
[INFO] 	at com.alexecollins.docker.orchestration.DockerOrchestrator.build(DockerOrchestrator.java:332)
[INFO] 	at com.alexecollins.docker.orchestration.DockerOrchestrator.build(DockerOrchestrator.java:789)
[INFO] 	at com.alexecollins.docker.mojo.PackageMojo.doExecute(PackageMojo.java:16)
[INFO] 	at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:162)
[INFO] 	... 21 more
[INFO] Caused by: java.nio.file.DirectoryNotEmptyException: /home/ubuntu/docker-maven-plugin/target/it/build-test-it/target/docker/app
[INFO] 	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:557)
[INFO] 	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
[INFO] 	at java.nio.file.Files.copy(Files.java:1227)
[INFO] 	at com.alexecollins.docker.orchestration.FileOrchestrator.copyFileEntry(FileOrchestrator.java:90)
[INFO] 	at com.alexecollins.docker.orchestration.FileOrchestrator.prepare(FileOrchestrator.java:76)
[INFO] 	at com.alexecollins.docker.orchestration.DockerOrchestrator.prepare(DockerOrchestrator.java:353)
[INFO] 	at com.alexecollins.docker.orchestration.DockerOrchestrator.build(DockerOrchestrator.java:330)
[INFO] 	... 24 more
~~~

Which indicates a problem with this code:

~~~
    private void copyFileEntry(final File destDir, File fileEntry) throws IOException {
        LOGGER.info(" - add " + fileEntry);
        if (fileEntry.isDirectory()) {
            copyDirectoryToDirectory(fileEntry, destDir);
        } else {
            Files.copy(fileEntry.toPath(), destDir.toPath(),
                    StandardCopyOption.COPY_ATTRIBUTES,
                    StandardCopyOption.REPLACE_EXISTING);
        }
    }
~~~

Any chance you could take a look at it?

**Comment by marcust** [comment]
I'll have a look

**Comment by marcust** [comment]
This is fixed, isn't it?
